### PR TITLE
Add Apache-2 license header to the EdgeImpulse source code

### PR DESCRIPTION
**Pull request by tomoveu**
This PR clarifies the existing Apache-2 license of the EdgeImpulse source code by adding Apache-2 license header to every EdgeImpulse source code file.

 Signed-off-by: Dimitar Tomov <dimi@edgeimpulse.com>

### CODE REVIEW

**Review by automatiek — CHANGES_REQUESTED** [review]
I see still a lot of MIT headers. And files without a header, most of them in fw-sdk.

**Comment by tomoveu** [comment]
@automatiek I thought the change is needed only for our Firmware, since the fw-sdk is a clone of our monorepo.

**Comment by tomoveu** [comment]
@automatiek fw-sdk license headers updated to Apache-2 , could you please re-review

**Review by automatiek — COMMENTED** [review]
Still 2 files in fw-sdk/jpeg

**Comment by automatiek** [comment]
but after that you can merge!

**Comment by tomoveu** [comment]
Thank you @automatiek 🚀 The 2 files in fw-sdk/jpeg were also updated in a new commit. Merging now.

**Pull request merged**
